import type { Metadata } from "next"

const address = {
  streetAddress: "Rua José Versolato, nº 111, BL B - 11° andar – Cj. 1101",
  addressLocality: "São Bernardo do Campo",
  addressRegion: "SP",
  postalCode: "09750-730",
  addressCountry: "BR",
}

const fullAddress = `${address.streetAddress}, Centro - ${address.addressLocality} - ${address.addressRegion}, CEP ${address.postalCode}`

export const AREA_SERVED = [
  "São Bernardo do Campo",
  "ABC Paulista",
  "São Paulo",
  "Grande São Paulo",
  "Interior de São Paulo",
  "Brasil",
]

export const SEO = {
  siteName: "Lucimeire Xavier Advocacia",
  siteUrl: "https://www.lucimeirexavieradvocacia.adv.br",
  locale: "pt_BR",
  defaultTitle: "Advogada Tributarista em São Paulo, ABC e Grande São Paulo",
  defaultDescription:
    "Assessoria em Direito Tributário para empresas e profissionais em São Paulo, no ABC e na Grande São Paulo, com base em São Bernardo do Campo — planejamento tributário, execução fiscal, consultoria fiscal e prevenção de riscos tributários.",
  phoneDisplay: "(11) 96758-6911",
  phoneIntl: "+55-11-96758-6911",
  email: "contato@lucimeirexavieradvocacia.adv.br",
  /** Default social preview (generated by app/opengraph-image.tsx). */
  ogImagePath: "/opengraph-image",
  ogImageAlt:
    "Lucimeire Xavier Advocacia — Direito Tributário em São Paulo, ABC e Grande São Paulo",
  address,
  fullAddress,
  mapsUrl: `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(fullAddress)}`,
  sameAs: [
    "https://www.instagram.com/dra.lucimeirexavier",
    "https://www.facebook.com/share/1AuufW4tkE/",
    "https://www.linkedin.com/in/lucimeire-xavier/",
    "https://www.youtube.com/@lucimeirexavier4203",
    "https://www.tiktok.com/@lucimeirexavier",
  ],
} as const

export const defaultOgImages = [
  {
    url: SEO.ogImagePath,
    width: 1200,
    height: 630,
    alt: SEO.ogImageAlt,
  },
] as const

type PageMetadataInput = {
  title: string
  description: string
  path: string
  keywords?: string[]
}

export function canonicalUrl(path: string) {
  return new URL(path, SEO.siteUrl).toString()
}

export function createPageMetadata(input: PageMetadataInput): Metadata {
  const url = canonicalUrl(input.path)
  return {
    title: input.title,
    description: input.description,
    keywords: input.keywords,
    alternates: { canonical: input.path },
    openGraph: {
      type: "website",
      locale: SEO.locale,
      siteName: SEO.siteName,
      title: input.title,
      description: input.description,
      url,
      images: [...defaultOgImages],
    },
    twitter: {
      card: "summary_large_image",
      title: input.title,
      description: input.description,
      images: [SEO.ogImagePath],
    },
  }
}

export function createBlogPostMetadata(input: {
  title: string
  description: string
  path: string
}): Metadata {
  const url = canonicalUrl(input.path)

  return {
    title: input.title,
    description: input.description,
    alternates: {
      canonical: input.path,
    },
    openGraph: {
      type: "article",
      locale: SEO.locale,
      siteName: SEO.siteName,
      title: input.title,
      description: input.description,
      url,
      images: [...defaultOgImages],
    },
    twitter: {
      card: "summary_large_image",
      title: input.title,
      description: input.description,
      images: [SEO.ogImagePath],
    },
  }
}

const areaPages: Record<string, { title: string; description: string; keywords: string[] }> = {
  "direito-tributario": {
    title: "Advogada Tributarista em São Bernardo do Campo",
    description:
      "Advogada tributarista em São Bernardo do Campo e no ABC para empresas e profissionais. Atuação em planejamento tributário, consultoria fiscal, execução fiscal e contencioso tributário.",
    keywords: [
      "direito tributário",
      "advogada tributarista",
      "advogada tributarista são bernardo do campo",
      "advogado tributário são bernardo do campo",
      "advogada tributarista abc",
      "advogada tributarista são paulo",
      "advogada tributarista grande são paulo",
      "consultoria tributária abc",
      "planejamento tributário",
      "execução fiscal",
      "consultoria fiscal",
      "São Bernardo do Campo",
      "São Paulo",
    ],
  },
  "direito-empresarial": {
    title: "Direito Empresarial em São Bernardo do Campo",
    description:
      "Consultoria em Direito Empresarial para empresas em São Bernardo do Campo, com apoio em contratos comerciais, compliance, estrutura societária e decisões com reflexo tributário.",
    keywords: [
      "direito empresarial",
      "advogado empresarial são bernardo do campo",
      "contratos comerciais",
      "compliance empresarial",
    ],
  },
  "direito-civil": {
    title: "Direito Civil e Contratos em São Bernardo do Campo",
    description:
      "Atuação em Direito Civil com suporte em contratos, responsabilidade civil e proteção patrimonial, com atendimento em São Bernardo do Campo.",
    keywords: [
      "direito civil",
      "advogado civil são bernardo do campo",
      "contratos civis",
      "responsabilidade civil",
    ],
  },
  "direito-imobiliario": {
    title: "Direito Imobiliário em São Bernardo do Campo",
    description:
      "Assessoria em Direito Imobiliário para compra e venda, locações e regularização de imóveis em São Bernardo do Campo, com atenção a risco patrimonial e impacto tributário.",
    keywords: [
      "direito imobiliário",
      "advogado imobiliário são bernardo do campo",
      "compra e venda de imóveis",
      "locação",
      "regularização",
    ],
  },
  "direito-trabalhista": {
    title: "Direito Trabalhista em São Bernardo do Campo",
    description:
      "Atendimento em Direito Trabalhista para rescisões, ações trabalhistas e consultoria preventiva em São Bernardo do Campo, com foco em redução de passivo e organização da operação.",
    keywords: [
      "direito trabalhista",
      "advogado trabalhista são bernardo do campo",
      "ações trabalhistas",
      "consultoria trabalhista",
    ],
  },
  "direito-processual": {
    title: "Direito Processual e Estratégia Processual",
    description:
      "Representação em processos judiciais e administrativos, com foco em estratégia processual, recursos, execuções e disputas com impacto tributário em São Bernardo do Campo.",
    keywords: [
      "direito processual",
      "advogado processual são bernardo do campo",
      "ações judiciais",
      "recursos",
      "execuções",
    ],
  },
  "consultoria-juridica": {
    title: "Consultoria Jurídica Preventiva em São Bernardo do Campo",
    description:
      "Consultoria jurídica preventiva para empresas e profissionais, com pareceres, due diligence e suporte estratégico em São Bernardo do Campo.",
    keywords: [
      "consultoria jurídica",
      "consultoria jurídica empresarial",
      "parecer jurídico",
      "due diligence",
    ],
  },
  "direito-previdenciario": {
    title: "Direito Previdenciário em São Bernardo do Campo e São Paulo",
    description:
      "Atuação em Direito Previdenciário para aposentadorias, revisões de benefício, contribuições recolhidas acima do teto e recuperação de INSS, com atendimento em São Bernardo do Campo, São Paulo e Grande São Paulo.",
    keywords: [
      "direito previdenciário",
      "advogado previdenciário são bernardo do campo",
      "advogada previdenciária são paulo",
      "revisão de aposentadoria",
      "recuperação de inss",
      "inss acima do teto",
      "revisão do fap",
      "gilrat rat",
    ],
  },
  inventario: {
    title: "Inventário e Planejamento Sucessório em São Bernardo do Campo e São Paulo",
    description:
      "Assessoria em inventário judicial e extrajudicial, partilha, holding familiar e planejamento sucessório, com atenção ao impacto tributário do ITCMD e do ganho de capital em São Bernardo do Campo, São Paulo e Grande São Paulo.",
    keywords: [
      "inventário",
      "advogado inventário são bernardo do campo",
      "advogada inventário são paulo",
      "inventário extrajudicial",
      "partilha de bens",
      "planejamento sucessório",
      "holding familiar",
      "itcmd",
    ],
  },
}

export function createAreaMetadata(slug: keyof typeof areaPages): Metadata {
  const data = areaPages[slug]
  return createPageMetadata({
    title: data.title,
    description: data.description,
    path: `/areas/${slug}`,
    keywords: data.keywords,
  })
}

export function buildLegalServiceSchema() {
  return {
    "@context": "https://schema.org",
    "@type": "LegalService",
    "@id": `${SEO.siteUrl}/#legalservice`,
    name: SEO.siteName,
    url: SEO.siteUrl,
    image: [`${SEO.siteUrl}${SEO.ogImagePath}`, `${SEO.siteUrl}/images/logo.png`],
    telephone: SEO.phoneIntl,
    email: SEO.email,
    areaServed: AREA_SERVED,
    serviceType: [
      "Direito Tributário",
      "Planejamento Tributário",
      "Consultoria Fiscal",
      "Contencioso Tributário",
    ],
    address: {
      "@type": "PostalAddress",
      ...SEO.address,
    },
    sameAs: SEO.sameAs,
  }
}

export function buildTaxServiceSchema() {
  return {
    "@context": "https://schema.org",
    "@type": "Service",
    "@id": `${SEO.siteUrl}/areas/direito-tributario#service`,
    serviceType: "Direito Tributário",
    name: "Assessoria em Direito Tributário",
    provider: {
      "@type": "LegalService",
      name: SEO.siteName,
      url: SEO.siteUrl,
    },
    areaServed: AREA_SERVED,
    offers: {
      "@type": "Offer",
      availability: "https://schema.org/InStock",
      url: `${SEO.siteUrl}/areas/direito-tributario`,
    },
    description:
      "Assessoria tributária para planejamento tributário, execuções fiscais, consultoria fiscal e contencioso tributário para empresas e profissionais.",
  }
}

export function buildAreaServiceSchema(input: {
  slug: string
  serviceType: string
  name: string
  description: string
}) {
  return {
    "@context": "https://schema.org",
    "@type": "Service",
    "@id": `${SEO.siteUrl}/areas/${input.slug}#service`,
    serviceType: input.serviceType,
    name: input.name,
    provider: {
      "@type": "LegalService",
      name: SEO.siteName,
      url: SEO.siteUrl,
    },
    areaServed: AREA_SERVED,
    offers: {
      "@type": "Offer",
      availability: "https://schema.org/InStock",
      url: `${SEO.siteUrl}/areas/${input.slug}`,
    },
    description: input.description,
  }
}

export function buildBlogPostingSchema(input: {
  title: string
  description: string
  slug: string
  datePublished: string
  author?: string
  category?: string
}) {
  return {
    "@context": "https://schema.org",
    "@type": "BlogPosting",
    headline: input.title,
    description: input.description,
    datePublished: input.datePublished,
    dateModified: input.datePublished,
    inLanguage: "pt-BR",
    articleSection: input.category,
    author: {
      "@type": "Person",
      name: input.author || "Dra. Lucimeire Xavier",
    },
    publisher: {
      "@type": "Organization",
      name: SEO.siteName,
      url: SEO.siteUrl,
    },
    mainEntityOfPage: canonicalUrl(`/blog/${input.slug}`),
    url: canonicalUrl(`/blog/${input.slug}`),
  }
}

export function buildLocalOfficeSchema(input: {
  path: string
  serviceName: string
  description: string
}) {
  const url = canonicalUrl(input.path)

  return {
    "@context": "https://schema.org",
    "@type": "LegalService",
    "@id": `${url}#local-office`,
    name: SEO.siteName,
    url,
    image: `${SEO.siteUrl}/images/logo.png`,
    telephone: SEO.phoneIntl,
    email: SEO.email,
    areaServed: AREA_SERVED,
    address: {
      "@type": "PostalAddress",
      ...SEO.address,
    },
    hasOfferCatalog: {
      "@type": "OfferCatalog",
      name: input.serviceName,
      itemListElement: [
        {
          "@type": "Offer",
          itemOffered: {
            "@type": "Service",
            name: input.serviceName,
            description: input.description,
          },
        },
      ],
    },
    sameAs: SEO.sameAs,
  }
}

export function buildServiceSchema(input: {
  path: string
  serviceType: string
  name: string
  description: string
}) {
  const url = canonicalUrl(input.path)

  return {
    "@context": "https://schema.org",
    "@type": "Service",
    "@id": `${url}#service`,
    serviceType: input.serviceType,
    name: input.name,
    provider: {
      "@type": "LegalService",
      name: SEO.siteName,
      url: SEO.siteUrl,
    },
    areaServed: AREA_SERVED,
    offers: {
      "@type": "Offer",
      availability: "https://schema.org/InStock",
      url,
    },
    description: input.description,
  }
}

export function buildItemListSchema(input: {
  path: string
  name: string
  description: string
  items: Array<{ name: string }>
}) {
  const url = canonicalUrl(input.path)

  return {
    "@context": "https://schema.org",
    "@type": "ItemList",
    "@id": `${url}#teses`,
    name: input.name,
    description: input.description,
    url,
    numberOfItems: input.items.length,
    itemListElement: input.items.map((item, index) => ({
      "@type": "ListItem",
      position: index + 1,
      name: item.name,
    })),
  }
}

export function buildFaqSchema(
  questions: Array<{
    question: string
    answer: string
  }>
) {
  return {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    mainEntity: questions.map((item) => ({
      "@type": "Question",
      name: item.question,
      acceptedAnswer: {
        "@type": "Answer",
        text: item.answer,
      },
    })),
  }
}
